-- ====================================================================
-- FICHERO 2: CREACIÓN DE TABLAS FÍSICAS (MODIFICADO CON IDENTITY)
-- ====================================================================

-- 1. Visitantes (Ahora con autoincremento automático) [cite: 268, 316]
CREATE TABLE Visitantes (
    id_visitante NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    dni_pasaporte VARCHAR2(10),
    telefono VARCHAR2(20)
);

-- 2. Empleados
CREATE TABLE Empleados (
    id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    cargo VARCHAR2(50),
    telefono VARCHAR2(20),
    fecha_contrato DATE,
    en_activo CHAR(1) CHECK (en_activo IN ('S', 'N'))
);

-- 3. Recintos
CREATE TABLE Recintos (
    id_recinto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_sector VARCHAR2(50),
    tipo_seguridad VARCHAR2(50),
    capacidad_max NUMBER,
    disponible CHAR(1) CHECK (disponible IN ('S', 'N')),
    historial_alertas T_Lista_Incidencias
) NESTED TABLE historial_alertas STORE AS tabla_alertas_almacenada;

-- 4. Dinosaurios (Nota: En tablas de objetos 'OF', el ID suele ser manual o vía OID)
CREATE TABLE Dinosaurios OF T_Dinosaurio (
    id_dino PRIMARY KEY
);

-- Añadimos la relación con el recinto
ALTER TABLE Dinosaurios ADD (
    id_recinto NUMBER,
    CONSTRAINT fk_dino_recinto FOREIGN KEY (id_recinto) REFERENCES Recintos(id_recinto)
);

-- 5. Registro de Visitas
CREATE TABLE Registro_Visitas (
    id_registro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_visitante NUMBER,
    id_recinto NUMBER,
    fecha_visita DATE,
    tipo_entrada VARCHAR2(20),
    estado VARCHAR2(20),
    CONSTRAINT fk_vis_visitante FOREIGN KEY (id_visitante) REFERENCES Visitantes(id_visitante),
    CONSTRAINT fk_vis_recinto FOREIGN KEY (id_recinto) REFERENCES Recintos(id_recinto)
);

-- 6. Servicios Extra
CREATE TABLE Servicios_Extra (
    id_servicio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    descripcion VARCHAR2(200),
    precio NUMBER(8,2)
);

-- 7. Ventas en el Parque
CREATE TABLE Ventas (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_registro NUMBER,
    id_servicio NUMBER,
    id_empleado NUMBER,
    total NUMBER(8,2),
    CONSTRAINT fk_ven_registro FOREIGN KEY (id_registro) REFERENCES Registro_Visitas(id_registro),
    CONSTRAINT fk_ven_servicio FOREIGN KEY (id_servicio) REFERENCES Servicios_Extra(id_servicio),
    CONSTRAINT fk_ven_empleado FOREIGN KEY (id_empleado) REFERENCES Empleados(id_empleado)
);

-- 8. Pagos
CREATE TABLE Pago (
    id_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_registro NUMBER,
    fecha_pago DATE,
    cantidad NUMBER(8,2),
    metodo VARCHAR2(20),
    CONSTRAINT fk_pago_registro FOREIGN KEY (id_registro) REFERENCES Registro_Visitas(id_registro)
);